// Code generated by goctl. DO NOT EDIT.
package types

type UserEmailRequest struct {
	Email string `form:"email"`
}

type UserEmailResponse struct {
	Code   string `json:"code"`
	Status int    `json:"status,default=1"`
}

type UserRegisterRequest struct {
	UserName     string `form:"user_name"`
	UserPassword string `form:"user_password"`
	Email string `form:"email"`
	Code string `form:"code"`
}

type UserRegisterResponse struct {
	Message string `json:"message"`
}
