// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package server

import (
	"context"

	"zero-cloud-disk/app/file-rpc/internal/logic"
	"zero-cloud-disk/app/file-rpc/internal/svc"
	"zero-cloud-disk/app/file-rpc/pb"
)

type FilecenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedFilecenterServer
}

func NewFilecenterServer(svcCtx *svc.ServiceContext) *FilecenterServer {
	return &FilecenterServer{
		svcCtx: svcCtx,
	}
}

func (s *FilecenterServer) GetFileInfo(ctx context.Context, in *pb.FileInfoReq) (*pb.FileInfoRes, error) {
	l := logic.NewGetFileInfoLogic(ctx, s.svcCtx)
	return l.GetFileInfo(in)
}

func (s *FilecenterServer) FileDownload(ctx context.Context, in *pb.FileDownloadReq) (*pb.FileDownloadRes, error) {
	l := logic.NewFileDownloadLogic(ctx, s.svcCtx)
	return l.FileDownload(in)
}

func (s *FilecenterServer) FileModify(ctx context.Context, in *pb.FileModifyReq) (*pb.FileModifyRes, error) {
	l := logic.NewFileModifyLogic(ctx, s.svcCtx)
	return l.FileModify(in)
}

func (s *FilecenterServer) FileMove(ctx context.Context, in *pb.FileMoveReq) (*pb.FileMoveRes, error) {
	l := logic.NewFileMoveLogic(ctx, s.svcCtx)
	return l.FileMove(in)
}

func (s *FilecenterServer) FileDelete(ctx context.Context, in *pb.FileDeleteReq) (*pb.FileDeleteRes, error) {
	l := logic.NewFileDeleteLogic(ctx, s.svcCtx)
	return l.FileDelete(in)
}

func (s *FilecenterServer) FileDeleteForever(ctx context.Context, in *pb.DeleteForeverReq) (*pb.DeleteForeverRes, error) {
	l := logic.NewFileDeleteForeverLogic(ctx, s.svcCtx)
	return l.FileDeleteForever(in)
}

func (s *FilecenterServer) FileDeleteAllForever(ctx context.Context, in *pb.DeleteAllForeverReq) (*pb.DeleteAllForeverRes, error) {
	l := logic.NewFileDeleteAllForeverLogic(ctx, s.svcCtx)
	return l.FileDeleteAllForever(in)
}

func (s *FilecenterServer) FileListByPath(ctx context.Context, in *pb.FileListByPathReq) (*pb.FileListByPathRes, error) {
	l := logic.NewFileListByPathLogic(ctx, s.svcCtx)
	return l.FileListByPath(in)
}

func (s *FilecenterServer) CreateFolder(ctx context.Context, in *pb.CreateFolderReq) (*pb.CreateFolderRes, error) {
	l := logic.NewCreateFolderLogic(ctx, s.svcCtx)
	return l.CreateFolder(in)
}

func (s *FilecenterServer) FileRecycleList(ctx context.Context, in *pb.FileRecycleListReq) (*pb.FileRecycleListRes, error) {
	l := logic.NewFileRecycleListLogic(ctx, s.svcCtx)
	return l.FileRecycleList(in)
}
