// Code generated by goctl. DO NOT EDIT.
package types

type CancelFileShareRequest struct {
	ShareUuid string `form:"share_uuid"`
}

type CancelFileShareResponse struct {
	Message string `json:"message"`
}

type FileShareRequest struct {
	FileHash  string `form:"file_hash,optional"`
	UserEmail string `form:"user_email"`
	UserName  string `form:"user_name"`
	Path      string `form:"path,optional"`
	ShareUuid string `form:"share_uuid"`
	Duration  int    `form:"duration,optional"`
}

type FileShareResponse struct {
	Message string `json:"message"`
}

type GetShareRequest struct {
	ShareUuid string `form:"share_uuid"`
}

type GetShareResponse struct {
	Data interface{} `json:"data"`
}
