// Code generated by goctl. DO NOT EDIT.
// Source: share.proto

package sharecenter

import (
	"context"

	"zero-cloud-disk/app/share-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CancelFileShareReq = pb.CancelFileShareReq
	CancelFileShareRes = pb.CancelFileShareRes
	FileShareReq       = pb.FileShareReq
	FileShareRes       = pb.FileShareRes
	GetShareReq        = pb.GetShareReq
	SaveFileReq        = pb.SaveFileReq
	SaveFileRes        = pb.SaveFileRes
	SharedFile         = pb.SharedFile
	SharedFiles        = pb.SharedFiles

	Sharecenter interface {
		FileShare(ctx context.Context, in *FileShareReq, opts ...grpc.CallOption) (*FileShareRes, error)
		CancelFileShare(ctx context.Context, in *CancelFileShareReq, opts ...grpc.CallOption) (*CancelFileShareRes, error)
		GetFileShare(ctx context.Context, in *GetShareReq, opts ...grpc.CallOption) (*SharedFiles, error)
		SaveFileShare(ctx context.Context, in *SaveFileReq, opts ...grpc.CallOption) (*SaveFileRes, error)
	}

	defaultSharecenter struct {
		cli zrpc.Client
	}
)

func NewSharecenter(cli zrpc.Client) Sharecenter {
	return &defaultSharecenter{
		cli: cli,
	}
}

func (m *defaultSharecenter) FileShare(ctx context.Context, in *FileShareReq, opts ...grpc.CallOption) (*FileShareRes, error) {
	client := pb.NewSharecenterClient(m.cli.Conn())
	return client.FileShare(ctx, in, opts...)
}

func (m *defaultSharecenter) CancelFileShare(ctx context.Context, in *CancelFileShareReq, opts ...grpc.CallOption) (*CancelFileShareRes, error) {
	client := pb.NewSharecenterClient(m.cli.Conn())
	return client.CancelFileShare(ctx, in, opts...)
}

func (m *defaultSharecenter) GetFileShare(ctx context.Context, in *GetShareReq, opts ...grpc.CallOption) (*SharedFiles, error) {
	client := pb.NewSharecenterClient(m.cli.Conn())
	return client.GetFileShare(ctx, in, opts...)
}

func (m *defaultSharecenter) SaveFileShare(ctx context.Context, in *SaveFileReq, opts ...grpc.CallOption) (*SaveFileRes, error) {
	client := pb.NewSharecenterClient(m.cli.Conn())
	return client.SaveFileShare(ctx, in, opts...)
}
