// Code generated by goctl. DO NOT EDIT.
// Source: file.proto

package filecenter

import (
	"context"

	"zero-cloud-disk/app/file-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateFolderReq     = pb.CreateFolderReq
	CreateFolderRes     = pb.CreateFolderRes
	DeleteAllForeverReq = pb.DeleteAllForeverReq
	DeleteAllForeverRes = pb.DeleteAllForeverRes
	DeleteForeverReq    = pb.DeleteForeverReq
	DeleteForeverRes    = pb.DeleteForeverRes
	File                = pb.File
	FileDeleteReq       = pb.FileDeleteReq
	FileDeleteRes       = pb.FileDeleteRes
	FileDownloadReq     = pb.FileDownloadReq
	FileDownloadRes     = pb.FileDownloadRes
	FileInfoReq         = pb.FileInfoReq
	FileInfoRes         = pb.FileInfoRes
	FileListByPathReq   = pb.FileListByPathReq
	FileListByPathRes   = pb.FileListByPathRes
	FileModifyReq       = pb.FileModifyReq
	FileModifyRes       = pb.FileModifyRes
	FileMoveReq         = pb.FileMoveReq
	FileMoveRes         = pb.FileMoveRes
	FileRecycleListReq  = pb.FileRecycleListReq
	FileRecycleListRes  = pb.FileRecycleListRes
	RecycleFile         = pb.RecycleFile

	Filecenter interface {
		GetFileInfo(ctx context.Context, in *FileInfoReq, opts ...grpc.CallOption) (*FileInfoRes, error)
		FileDownload(ctx context.Context, in *FileDownloadReq, opts ...grpc.CallOption) (*FileDownloadRes, error)
		FileModify(ctx context.Context, in *FileModifyReq, opts ...grpc.CallOption) (*FileModifyRes, error)
		FileMove(ctx context.Context, in *FileMoveReq, opts ...grpc.CallOption) (*FileMoveRes, error)
		FileDelete(ctx context.Context, in *FileDeleteReq, opts ...grpc.CallOption) (*FileDeleteRes, error)
		FileDeleteForever(ctx context.Context, in *DeleteForeverReq, opts ...grpc.CallOption) (*DeleteForeverRes, error)
		FileDeleteAllForever(ctx context.Context, in *DeleteAllForeverReq, opts ...grpc.CallOption) (*DeleteAllForeverRes, error)
		FileListByPath(ctx context.Context, in *FileListByPathReq, opts ...grpc.CallOption) (*FileListByPathRes, error)
		CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderRes, error)
		FileRecycleList(ctx context.Context, in *FileRecycleListReq, opts ...grpc.CallOption) (*FileRecycleListRes, error)
	}

	defaultFilecenter struct {
		cli zrpc.Client
	}
)

func NewFilecenter(cli zrpc.Client) Filecenter {
	return &defaultFilecenter{
		cli: cli,
	}
}

func (m *defaultFilecenter) GetFileInfo(ctx context.Context, in *FileInfoReq, opts ...grpc.CallOption) (*FileInfoRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.GetFileInfo(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDownload(ctx context.Context, in *FileDownloadReq, opts ...grpc.CallOption) (*FileDownloadRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDownload(ctx, in, opts...)
}

func (m *defaultFilecenter) FileModify(ctx context.Context, in *FileModifyReq, opts ...grpc.CallOption) (*FileModifyRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileModify(ctx, in, opts...)
}

func (m *defaultFilecenter) FileMove(ctx context.Context, in *FileMoveReq, opts ...grpc.CallOption) (*FileMoveRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileMove(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDelete(ctx context.Context, in *FileDeleteReq, opts ...grpc.CallOption) (*FileDeleteRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDelete(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDeleteForever(ctx context.Context, in *DeleteForeverReq, opts ...grpc.CallOption) (*DeleteForeverRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDeleteForever(ctx, in, opts...)
}

func (m *defaultFilecenter) FileDeleteAllForever(ctx context.Context, in *DeleteAllForeverReq, opts ...grpc.CallOption) (*DeleteAllForeverRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileDeleteAllForever(ctx, in, opts...)
}

func (m *defaultFilecenter) FileListByPath(ctx context.Context, in *FileListByPathReq, opts ...grpc.CallOption) (*FileListByPathRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileListByPath(ctx, in, opts...)
}

func (m *defaultFilecenter) CreateFolder(ctx context.Context, in *CreateFolderReq, opts ...grpc.CallOption) (*CreateFolderRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.CreateFolder(ctx, in, opts...)
}

func (m *defaultFilecenter) FileRecycleList(ctx context.Context, in *FileRecycleListReq, opts ...grpc.CallOption) (*FileRecycleListRes, error) {
	client := pb.NewFilecenterClient(m.cli.Conn())
	return client.FileRecycleList(ctx, in, opts...)
}
