// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"zero-cloud-disk/app/user-rpc/internal/logic"
	"zero-cloud-disk/app/user-rpc/internal/svc"
	"zero-cloud-disk/app/user-rpc/pb"
)

type UsercenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUsercenterServer
}

func NewUsercenterServer(svcCtx *svc.ServiceContext) *UsercenterServer {
	return &UsercenterServer{
		svcCtx: svcCtx,
	}
}

func (s *UsercenterServer) UserRegister(ctx context.Context, in *pb.UserRegisterReq) (*pb.UserRegisterRes, error) {
	l := logic.NewUserRegisterLogic(ctx, s.svcCtx)
	return l.UserRegister(in)
}

func (s *UsercenterServer) SendEmail(ctx context.Context, in *pb.UserEmailReq) (*pb.UserEmailRes, error) {
	l := logic.NewSendEmailLogic(ctx, s.svcCtx)
	return l.SendEmail(in)
}

func (s *UsercenterServer) GetUserInfo(ctx context.Context, in *pb.UserInfoReq) (*pb.UserInfoRes, error) {
	l := logic.NewGetUserInfoLogic(ctx, s.svcCtx)
	return l.GetUserInfo(in)
}

func (s *UsercenterServer) UserLogin(ctx context.Context, in *pb.UserLoginReq) (*pb.UserLoginRes, error) {
	l := logic.NewUserLoginLogic(ctx, s.svcCtx)
	return l.UserLogin(in)
}
