// Code generated by goctl. DO NOT EDIT.
// Source: share.proto

package server

import (
	"context"

	"zero-cloud-disk/app/share-rpc/internal/logic"
	"zero-cloud-disk/app/share-rpc/internal/svc"
	"zero-cloud-disk/app/share-rpc/pb"
)

type SharecenterServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedSharecenterServer
}

func NewSharecenterServer(svcCtx *svc.ServiceContext) *SharecenterServer {
	return &SharecenterServer{
		svcCtx: svcCtx,
	}
}

func (s *SharecenterServer) FileShare(ctx context.Context, in *pb.FileShareReq) (*pb.FileShareRes, error) {
	l := logic.NewFileShareLogic(ctx, s.svcCtx)
	return l.FileShare(in)
}

func (s *SharecenterServer) CancelFileShare(ctx context.Context, in *pb.CancelFileShareReq) (*pb.CancelFileShareRes, error) {
	l := logic.NewCancelFileShareLogic(ctx, s.svcCtx)
	return l.CancelFileShare(in)
}

func (s *SharecenterServer) GetFileShare(ctx context.Context, in *pb.GetShareReq) (*pb.SharedFiles, error) {
	l := logic.NewGetFileShareLogic(ctx, s.svcCtx)
	return l.GetFileShare(in)
}
