// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"zero-cloud-disk/app/user/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: userRegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/sendemail",
				Handler: sendEmailHandler(serverCtx),
			},
		},
	)
}
