// Code generated by goctl. DO NOT EDIT.
package types

type FileDownloadRequest struct {
	FileHash string `form:"file_hash"`
}

type FileDownloadResponse struct {
	Message string `json:"message"`
	FileName string `json:"file_name"`
	FilePath string `json:"file_path"`
}

type FileInfoRequest struct {
	FileHash string `form:"file_hash"`
}

type FileInfoResponse struct {
	FileName string `json:"file_name"`
	FileSize int64  `json:"file_size"`
	CreateAt string `json:"create_at"`
	UpdateAt string `json:"update_at"`
}

type FileUploadResponse struct {
	Message string `json:"message"`
}
